In [1]:
# Code snippet 1
# Installing Pycaret
!pip install git+https://github.com/pycaret/pycaret.git

Collecting git+https://github.com/pycaret/pycaret.git
  Cloning https://github.com/pycaret/pycaret.git to /tmp/pip-req-build-x7gwpcdr
  Running command git clone --filter=blob:none --quiet https://github.com/pycaret/pycaret.git /tmp/pip-req-build-x7gwpcdr
  Resolved https://github.com/pycaret/pycaret.git to commit 58ec3c282d58e94727f9d5b77b49f241e9103ab3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (7.34.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (7.7.1)
Requirement already satisfied: tqdm>=4.62.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (4.67.1)
Requirement already satisfied: numpy<1.27,>=1.21 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.26.4)
Requirement already satisfied: pandas<2.2 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.1.4)
Requirement already satisfied: jinja2>=3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.11.4)
Requirement already satisfied: joblib<1.5,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.4.2)
Requirement already satisfied: scikit-learn<1.5 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.0.5)
Requirement already satisfied: imbalanced-learn<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.13.0)
Requirement already satisfied: category-encoders>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.60.0)
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.32.4)
Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.9.5)
Requirement already satisfied: markupsafe>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.0.3)
Requirement already satisfied: importlib_metadata>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (8.7.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.10.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.1.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.6.0)
Requirement already satisfied: wurlitzer in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.1.1)
Requirement already satisfied: trio<0.25.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.24.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (75.2.0)
Requirement already satisfied: matplotlib<3.8.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (3.7.5)
Requirement already satisfied: mljar-scikit-plot in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.3.12)
Requirement already satisfied: yellowbrick>=1.4 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.5)
Requirement already satisfied: plotly>=5.14.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (5.24.1)
Requirement already satisfied: kaleido>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.2.0)
Requirement already satisfied: schemdraw==0.15 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.14.5)
Requirement already satisfied: sktime<0.31.1,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (0.31.0)
Requirement already satisfied: tbats>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from pycaret==3.4.0) (2.0.4)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category-encoders>=2.4.0->pycaret==3.4.0) (1.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->pycaret==3.4.0) (25.0)
Requirement already satisfied: sklearn-compat<1,>=0.1 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn<0.14.0,>=0.12.0->pycaret==3.4.0) (0.1.4)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn<0.14.0,>=0.12.0->pycaret==3.4.0) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata>=4.12.0->pycaret==3.4.0) (3.23.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.5.0->pycaret==3.4.0) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->pycaret==3.4.0) (3.0.16)
Requirement already satisfied: choreographer>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (3.11.4)
Requirement already satisfied: pytest-timeout>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from kaleido>=0.2.1->pycaret==3.4.0) (2.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (4.60.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (1.4.9)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.8.0->pycaret==3.4.0) (2.9.0.post0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat>=4.2.0->pycaret==3.4.0) (5.9.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.55.0->pycaret==3.4.0) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.2->pycaret==3.4.0) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.2->pycaret==3.4.0) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.14.0->pycaret==3.4.0) (8.5.0)
Requirement already satisfied: dash>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from plotly-resampler>=0.8.3.1->pycaret==3.4.0) (3.3.0)
Requirement already satisfied: tsdownsample>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from plotly-resampler>=0.8.3.1->pycaret==3.4.0) (0.1.4.1)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.12/dist-packages (from pmdarima>=2.0.4->pycaret==3.4.0) (3.0.12)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from pmdarima>=2.0.4->pycaret==3.4.0) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27.1->pycaret==3.4.0) (2025.10.5)
Requirement already satisfied: scikit-base<0.9.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from sktime<0.31.1,>=0.31.0->pycaret==3.4.0) (0.8.3)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<0.25.0,>=0.22.0->pycaret==3.4.0) (1.3.1)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret==3.4.0) (3.20.2)
Requirement already satisfied: Flask<3.2,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (3.1.3)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (4.15.0)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.6.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (7.4.9)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (6.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=5.5.0->pycaret==3.4.0) (0.8.5)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret==3.4.0) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret==3.4.0) (4.5.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=5.5.0->pycaret==3.4.0) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret==3.4.0) (0.2.14)
Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (8.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret==3.4.0) (1.17.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (6.5.7)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (8.3.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret==3.4.0) (2.2.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret==3.4.0) (0.4)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (25.1.0)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (7.16.6)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.23.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.3.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret==3.4.0) (1.6.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.5.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->pycaret==3.4.0) (2.8)

In [2]:
#code snippet 1
import pandas as pd
import numpy as np
# Specify the path to your CSV file
url = 'https://docs.google.com/spreadsheets/d/1XSBE7VwTJ-xB300r2JAwZesaAbGTLvMgS4qRxXfDjys/pub?gid=0&single=true&output=csv'
# Read the CSV file into a pandas DataFrame
data = pd.read_csv(url)
data.shape
# Display the first few rows of the DataFrame to verify
# display(data.head())

(16519, 21)

In [3]:
# Code snippet 3
# Display the data columns
data.columns

Index(['Customer ID', 'Title', 'First Name', 'Middle Name', 'Last Name',
       'Suffix', 'Street Address1', 'Street Address2', 'City-ZipCode-State',
       'Birth Date', 'Education Level', 'Occupation', 'Gender',
       'Marital Status', 'Home Owner Status', 'Number of Cars Owned',
       'Number of Children At Home', 'Total Number of Children',
       'Annual Income', 'Avg Monthly Spend', 'eBook Subscriber Flag'],
      dtype='object')

In [4]:
#derive age from birthdate
from datetime import datetime
today = datetime.now()
# Convert 'Birth Date' to datetime objects with explicit format
data['Birth Date'] = pd.to_datetime(data['Birth Date'], format='%m/%d/%y')

# Correct birth years that are in the future due to two-digit year interpretation
# If a birth year is after the current year, subtract 100 years
data.loc[data['Birth Date'].dt.year > today.year, 'Birth Date'] -= pd.offsets.DateOffset(years=100)

# Calculate age based on current date, using only the year part
data['Age'] = today.year - data['Birth Date'].dt.year

# Filter data where 'Birth Date' is less than or equal to today and make an explicit copy
dataa = data[data['Birth Date'] <= today].copy()
dataa

,Customer ID,Title,First Name,Middle Name,Last Name,Suffix,Street Address1,Street Address2,City-ZipCode-State,Birth Date,...,Gender,Marital Status,Home Owner Status,Number of Cars Owned,Number of Children At Home,Total Number of Children,Annual Income,Avg Monthly Spend,eBook Subscriber Flag,Age
0,11000,NaN,Jon,V,Yang,NaN,3761 N. 14th St,NaN,Cleveland-44101-Ohio,1966-04-08,...,M,M,1,0,0,2,137947,89,0,59
1,11001,NaN,Eugene,L,Huang,NaN,2243 W St.,NaN,Seattle-98101-Washington,1965-05-14,...,M,S,0,1,3,3,101141,117,1,60
2,11002,NaN,Ruben,NaN,Torres,NaN,5844 Linden Land,NaN,Omaha-68101-Nebraska,1965-08-12,...,M,M,1,1,3,3,91945,123,0,60
3,11003,NaN,Christy,NaN,Zhu,NaN,1825 Village Pl.,NaN,Fort Worth-76101-Texas,1968-02-15,...,F,S,0,1,0,0,86688,50,0,57
4,11004,NaN,Elizabeth,NaN,Johnson,NaN,7553 Harness Circle,NaN,Oakland-94601-California,1968-08-08,...,F,S,1,4,5,5,92771,95,1,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16514,13121,NaN,Latasha,E,Jimenez,NaN,7259 Birchwood,NaN,San Antonio-78201-Texas,1965-03-22,...,F,M,1,4,5,5,101542,101,0,60
16515,26100,NaN,James,Garner,Ptaszynski,NaN,7345 Kenwal Rd.,NaN,Pittsburgh-15201-Pennsylvania,1936-04-02,...,F,S,1,2,0,3,46549,46,0,89
16516,11328,NaN,Julian,M,Griffin,NaN,7398 Withersed Lane,NaN,Honolulu-96801-Hawaii,1940-01-01,...,M,M,1,2,0,5,133053,79,0,85
16517,23077,NaN,Marvin,A,Hernandez,NaN,1019 Book Road,NaN,Anaheim-92801-California,1946-10-20,...,M,M,1,2,0,4,31930,65,0,79
16518,18982,NaN,Kyle,NaN,Baker,NaN,2118 Little Dr.,NaN,Fort Wayne-46801-Indiana,1945-04-07,...,M,S,1,2,0,4,59382,68,0,80

In [5]:
#code snippet 3.2
#separate City-ZipCode-State into 3 varaibles:
dataa[['City', 'ZipCode', 'State']]=dataa['City-ZipCode-State'].str.split('-', expand=True)

Predictive Analysis
Target Variable ='Avg Monthly Spend'

In [6]:
# Code snippet 4
# Predictive analysis of Target1: Avg Monthly Spend
# Setting the target variable
y = 'Avg Monthly Spend'

In [7]:
# Code snippet 5
# Setting the ignored variables list (noise/redundant/feeder and variables that are more than 20% data)
ignored_cols = ['Customer ID', 'First Name', 'Last Name', 'Street Address1','Title',
                 'Middle Name', 'Suffix', 'Street Address2','Birth Date','City', 'State','City-ZipCode-State','eBook Subscriber Flag']

In [8]:
# Code snippet 6
# Setting the categorical variables
cat_cols = ['Education Level', 'Occupation', 'Gender', 'Marital Status', 'Home Owner Status', 'ZipCode']

In [9]:
# Code snippet 7
# Setting the numerical columns
num_cols = ['Number of Cars Owned', 'Number of Children At Home',
            'Total Number of Children', 'Annual Income', 'Age']

In [10]:
# Code snippet 8
# Importing regression modules from pycaret
from pycaret.regression import *

In [11]:
# Code snippet 9
# Setting/configuring the ML experiment
regression_setup = setup(dataa,
                        target=y,
                        ignore_features=ignored_cols,
                        categorical_features=cat_cols,
                         numeric_features=num_cols,
                        train_size=0.8)

In [12]:
# Code snippet 10
# Invoking ML algorithms
compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

LGBMRegressor(n_jobs=-1, random_state=1007)

In [13]:
# Code snippet 11
# Building an ML model with the best algo from the leaderboard above
best_model = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [14]:
# Code snippet for tuning the best model
tuned_model = tune_model(best_model)

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [15]:
# Code snippet 12
# Predicting the standard scores using the best model
predicted_AvgMonthlySpend_best = predict_model(best_model, dataa)

# Exporting the predictions to a csv file
predicted_AvgMonthlySpend_best.to_csv('eBook Store Avg Monthly Spend Prediction.csv')

In [16]:
# Predicting the standard scores using the tuned model
predicted_AvgMonthlySpend_tuned = predict_model(tuned_model, dataa)

# Exporting the predictions to a csv file
predicted_AvgMonthlySpend_tuned.to_csv('eBook Store Avg Monthly Spend Prediction tuned.csv')

In [17]:
# Code snippet 13
# Displaying the prediction scores
predicted_AvgMonthlySpend_best

,Customer ID,Title,First Name,Middle Name,Last Name,Suffix,Street Address1,Street Address2,City-ZipCode-State,Birth Date,...,Number of Children At Home,Total Number of Children,Annual Income,eBook Subscriber Flag,Age,City,ZipCode,State,Avg Monthly Spend,prediction_label
0,11000,NaN,Jon,V,Yang,NaN,3761 N. 14th St,NaN,Cleveland-44101-Ohio,1966-04-08,...,0,2,137947,0,59,Cleveland,44101,Ohio,89,87.879766
1,11001,NaN,Eugene,L,Huang,NaN,2243 W St.,NaN,Seattle-98101-Washington,1965-05-14,...,3,3,101141,1,60,Seattle,98101,Washington,117,115.917793
2,11002,NaN,Ruben,NaN,Torres,NaN,5844 Linden Land,NaN,Omaha-68101-Nebraska,1965-08-12,...,3,3,91945,0,60,Omaha,68101,Nebraska,123,125.504520
3,11003,NaN,Christy,NaN,Zhu,NaN,1825 Village Pl.,NaN,Fort Worth-76101-Texas,1968-02-15,...,0,0,86688,0,57,Fort Worth,76101,Texas,50,49.645343
4,11004,NaN,Elizabeth,NaN,Johnson,NaN,7553 Harness Circle,NaN,Oakland-94601-California,1968-08-08,...,5,5,92771,1,57,Oakland,94601,California,95,92.660945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16514,13121,NaN,Latasha,E,Jimenez,NaN,7259 Birchwood,NaN,San Antonio-78201-Texas,1965-03-22,...,5,5,101542,0,60,San Antonio,78201,Texas,101,101.810777
16515,26100,NaN,James,Garner,Ptaszynski,NaN,7345 Kenwal Rd.,NaN,Pittsburgh-15201-Pennsylvania,1936-04-02,...,0,3,46549,0,89,Pittsburgh,15201,Pennsylvania,46,39.966275
16516,11328,NaN,Julian,M,Griffin,NaN,7398 Withersed Lane,NaN,Honolulu-96801-Hawaii,1940-01-01,...,0,5,133053,0,85,Honolulu,96801,Hawaii,79,79.283415
16517,23077,NaN,Marvin,A,Hernandez,NaN,1019 Book Road,NaN,Anaheim-92801-California,1946-10-20,...,0,4,31930,0,79,Anaheim,92801,California,65,63.380750
16518,18982,NaN,Kyle,NaN,Baker,NaN,2118 Little Dr.,NaN,Fort Wayne-46801-Indiana,1945-04-07,...,0,4,59382,0,80,Fort Wayne,46801,Indiana,68,65.497665

In [18]:
#Code snippet 15
# Display the original 'Avg Monthly Spend', the prediction from the best model, and the prediction from the tuned model
comparison_df = dataa[['Avg Monthly Spend']].copy()
comparison_df['Prediction (Best Model)'] = predicted_AvgMonthlySpend_best['prediction_label']
comparison_df['Prediction (Tuned Model)'] = predicted_AvgMonthlySpend_tuned['prediction_label']

display(comparison_df.head())

   Avg Monthly Spend  Prediction (Best Model)  Prediction (Tuned Model)
0                 89                87.879766                 87.879766
1                117               115.917793                115.917793
2                123               125.504520                125.504520
3                 50                49.645343                 49.645343
4                 95                92.660945                 92.660945

Predictive Analysis
Target Variable ="eBook Subscriber Flag"

In [19]:
# Code snippet 16
# Predictive analysis of Target1: Avg Monthly Spend
# Setting the target variable
y = 'eBook Subscriber Flag'

In [20]:
# Code snippet 17
# Setting the ignored variables list (noise/redundant/feeder and variables that are more than 20% data)
ignored_cols = ['Customer ID', 'First Name', 'Last Name', 'Street Address1','Title',
                 'Middle Name', 'Suffix', 'Street Address2','Birth Date','City', 'State','City-ZipCode-State','Avg Monthly Spend']

In [21]:
# Code snippet 18
# Setting the categorical variables
cat_cols = ['Education Level', 'Occupation', 'Gender', 'Marital Status', 'Home Owner Status', 'ZipCode']

In [22]:
# Code snippet 19
# Setting the numerical columns
num_cols = ['Number of Cars Owned', 'Number of Children At Home',
            'Total Number of Children','Annual Income', 'Age']

In [23]:
# Code snippet 20
# Importing classification ML components from the Pycaret package
from pycaret.classification import *

In [24]:
# Code snippet 21
# Setting up/configuring the ML experiment
classification_setup = setup(dataa,
                             target = y,
                             numeric_features = num_cols,
                             categorical_features = cat_cols,
                             train_size = 0.8)

In [25]:
# Code snippet 22
# Invoking classification ML algorithms
compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=1781, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [26]:
# Code snippet 23
# Building an ML model with the best algo from the leaderboard above
best_model = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [27]:
# Code snippet 24
# Predicting the Readmit30 statuses using the best model
predicted_Subscription_status = predict_model(best_model, dataa)

# Exporting the predictions to a csv file
predicted_Subscription_status.to_csv('eBook Store Subscription Prediction.csv')

In [28]:
#Code snippet 25
# Display the original 'Avg Monthly Spend', the prediction from the best model, and the prediction from the tuned model
comparison_df = dataa[['eBook Subscriber Flag']].copy()
comparison_df['Prediction (Best Model)'] = predicted_Subscription_status['prediction_label']

In [29]:
display(comparison_df.head())

   eBook Subscriber Flag  Prediction (Best Model)
0                      0                        0
1                      1                        1
2                      0                        0
3                      0                        0
4                      1                        1

In [30]:
# code snippet26
#Code snippet for tuning the best model
tuned_model = tune_model(best_model)

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [31]:
# code snippet 27
#Predicting the Subscription_status using the tuned model
predicted_Subscription_status_tuned = predict_model(tuned_model, dataa)

# Exporting the predictions to a csv file
predicted_Subscription_status_tuned.to_csv('eBook Store Subscription Prediction tuned.csv')

[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_freq is set=3, subsample_freq=0 will be ignored. Current value: bagging_freq=3
[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8

In [32]:
#Code snippet 28
# Display the original 'eBook Subscriber Flag, the prediction from the best model, and the prediction from the tuned model
comparison_df = dataa[['eBook Subscriber Flag']].copy()
comparison_df['Prediction (Best Model)'] = predicted_Subscription_status['prediction_label']
comparison_df['Prediction (Tuned Model)'] = predicted_Subscription_status_tuned['prediction_label']

display(comparison_df.head())

   eBook Subscriber Flag  Prediction (Best Model)  Prediction (Tuned Model)
0                      0                        0                         0
1                      1                        1                         1
2                      0                        0                         1
3                      0                        0                         0
4                      1                        1                         1